# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.0.1";
    sha256 = "0zxc0apx1gcx361jlq8smc9pfdgmyjh6hpka8dypc9w23nlsh6yj";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1d6xnyxvfkp3kgi5ncd4328hg1pmjg0ca6ddgzcab2rikd3sy59v";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "8.0.0";
    sha256 = "1jlpa4ggl1gr5fs7fdcw04li3y3iy05w3klr9lrrlc7v8w76kq71";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "067xajb4c8ykd4xrqg05fa496c5rn332wrahizkmmdzbgwic7pvd";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.0";
    sha256 = "1m0gawiz8f5hc3li9vd5psddlygwgkiw13d7div87kmkf4idza8r";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "16cq7v2pizxxsbcpwh1rw8jb4m8nxk5rlhmch1dwnl18ymih6qjm";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.CommandLine";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0vsi02wfgh1j8hspi59d9sh2qqjzl6sdhzm8sa59havhfjcma6j0";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.EnvironmentVariables";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1f12d15p9wvk6g2fjqdlr76mmdzk76v0q8cs1him751qj10cq093";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.FileExtensions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "149gijhfw0xmgp2kb5w1gjnahplyf6071qzadij6qm6rrav76yrm";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Json";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0v8p9apx87yb2wv9a6ri5m25716m192m827mwly53fav0afhiqr9";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.UserSecrets";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1caarpiv2vz1bby4wi863lw5y7wj7qxni340f0w389m0qzzg858f";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.0";
    sha256 = "0i7qziz0iqmbk8zzln7kx9vd0lbx1x3va0yi3j1bgkjir13h78ps";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "08cjbfpky5ak55vy77ra59p1qnicwjq193r5bm33li3hzxjg9wzd";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.0";
    sha256 = "1zw0bpp5742jzx03wvqc8csnvsbgdqi0ls9jfc5i2vd3cl8b74pg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0is4y08k0p254jwjdp2mxm1n7sj476rbaxwmcdkvajixink5wwcx";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "8.0.1";
    sha256 = "1fy3lp39q00aa6i4bd2904ghnazpmvarl4ngv5r7yhmm29fmmiwv";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1xc55v913f2lnv05s1dgxa4ysmmwcqrypqzv3hm6vzalwcxsyhvn";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "8.0.0";
    sha256 = "15m4j6w9n8h0mj7hlfzb83hd3wn7aq1s7fxbicm16slsjfwzj82i";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1ynnj2mxx50axgnd4z94akwblb4wccfigcs5a4gp6d9mimzb09qg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "8.0.0";
    sha256 = "1idq65fxwcn882c06yci7nscy9i0rgw6mqjrl7362prvvsd9f15r";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1b84bblic6rfradgp7g8pvjm73w5happ9gk8iqb4jknzqa1l5y5n";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Physical";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "13cy2hqwhwh80gazscjzwypsa5mp3fwx47j02rc5bi8qq4l8wmjy";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileSystemGlobbing";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0pxv7vhd75ahh7y3dw3iglga5lbmqn511ijdvq27iy49jn46i1ya";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0nghqji4vr48qgf2yvf19k6sf30f62vi5d4mpvsmm14p49rx76ys";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "8.0.0";
    sha256 = "00d5dwmzw76iy8z40ly01hy9gly49a7rpf7k7m99vrid1kxp346h";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "167hp8aa67ffqzxwc4kkgp830klk9kkvmlfcin7b5vyj39f95pqw";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.0";
    sha256 = "0nppj34nmq25gnrg0wh1q22y4wdqbih4ax493f226azv8mkp9s1i";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1szp3b7vi8mcsl3a8hhf1rim78m065abdi283fyy6hh5yrxlza9z";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.0";
    sha256 = "1klcqhg3hk55hb6vmjiq2wgqidsl81aldw0li2z98lrwx26msrr6";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0xnv36gv231fhw4hb533ymm05gpzck72wblybdhlc975fqyxd37b";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0kir1g022nsxvqbdwj8r0crr3f34xa9yjcf4g4ygrxp65gwab8l2";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0zjify3gms1c404kpxqin3zxklgy2nl9f8cwph1slijdis4j3bjv";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Debug";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1ld1rwv7fmc7vjsn27f9ad0fv62y1km556j892zwdbcvz407gvxm";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventLog";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0s2r7x913diwpqypjyl0shzwq6wpkfxfzqin425nhhlkcr05jhj0";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventSource";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1j0xgsvrhf5rwq8r8sdqsbfbm7iblbh7zv31gad5s41qrfkv8mqn";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.0";
    sha256 = "0p50qn6zhinzyhq9sy5svnmqqwhw2jajs2pbjh9sah504wjvhscz";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "04ijzkpgnsyzgrv8l2yaqwcww0qm6fcmgin3ii0cw5xzhrja5zyr";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1qrq50v4psl5ygspk62bpnssdwzhmm3dl89nxbxv6a0hcpif6an7";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    sha256 = "0aldaz5aapngchgdr7dax9jw5wy7k7hmjgjpfgfv1wfif27jlkqm";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "100z5sw0yv9rzfkqmg4hnhpisg6gq3b8havdhdmphp0qx35hyj1l";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.0.1";
    sha256 = "01al6cfxp68dscl15z7rxfw9zvhm64dncsw09a1vmdkacsa2v6lr";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.0.1";
    sha256 = "0ppdkwy6s9p7x9jix3v4402wb171cdiibq7js7i13nxpdky7074p";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    sha256 = "0xrwysmrn4midrjal8g2hr1bbg38iyisl0svamb11arqws4w2bw7";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "9.0.1";
    sha256 = "0mcy0i7pnfpqm4pcaiyzzji4g0c8i3a5gjz28rrr28110np8304r";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "3.1.1";
    sha256 = "0ck51ndmaqflsri7yyw5792z42wsp91038rx2i6vg7z4r35vfvig";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.0.0";
    sha256 = "1p4lb53assyvsn6pak60zcq4r48wyb9kp0b8fkgkimab6zjm1j4g";
  })
  (fetchNuGet {
    pname = "Serilog.AspNetCore";
    version = "8.0.2";
    sha256 = "17fnrraijpmrnbj46r3kj2hpwz4qzrmsnwgmqj749b7acqdlf5ki";
  })
  (fetchNuGet {
    pname = "Serilog.Expressions";
    version = "5.0.0";
    sha256 = "109gyi638zak6710303i7l6910yxikfhbsmg378kpk999pqi7466";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Hosting";
    version = "8.0.0";
    sha256 = "10cgp4nsrzkld5yxnvkfkwd0wkc1m8m7p5z42w4sqd8f188n8i9q";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Logging";
    version = "8.0.0";
    sha256 = "087ab94sfhkj6h6x3cwwf66g456704faxnfyc4pi6shxk45b318s";
  })
  (fetchNuGet {
    pname = "Serilog.Formatting.Compact";
    version = "2.0.0";
    sha256 = "0y7vg2qji02riq7r0kgybarhkngw6gh3xw89w7c2hcmjawd96x3k";
  })
  (fetchNuGet {
    pname = "Serilog.Settings.Configuration";
    version = "8.0.2";
    sha256 = "0jaz0lw7rbx643vp44ih7292235qcli5wk3sx1zwx4y3mfvm0x48";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Console";
    version = "5.0.0";
    sha256 = "0qk5b9vfgzx00a1c2rnih2p3jlcc88vdi9ar5cpwv1jb09x6brah";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Debug";
    version = "2.0.0";
    sha256 = "1i7j870l47gan3gpnnlzkccn5lbm7518cnkp25a3g5gp9l0dbwpw";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.File";
    version = "5.0.0";
    sha256 = "097rngmgcrdfy7jy8j7dq3xaq2qky8ijwg0ws6bfv5lx0f3vvb0q";
  })
  (fetchNuGet {
    pname = "Spectre.Console";
    version = "0.49.1";
    sha256 = "0fhl96p3xjd5k1wwvhs80cp35rrlgnza6mw9vy0knhmf7ji9b95n";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Analyzer";
    version = "1.0.0";
    sha256 = "0hc9r85p13d8af17nrms2smaiyx38qxf6wkb487vmq760x28yv9s";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Cli";
    version = "0.49.1";
    sha256 = "110gj4731c77zddy2bqrym8b30pv6ypm6r1x6b1jpmpd2ypgvami";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Extensions.Progress";
    version = "1.0.0";
    sha256 = "09dwzy6cd9fji5fw0x4jayg9zk8bn48fmjrii9ynid4wjznas22v";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.0.11";
    sha256 = "1ga40f5lrwldiyw6vy67d0sg7jd7ww6kgwbksm19wrvq9hr0bsm6";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.0.11";
    sha256 = "0gmjghrqmlgzxivd2xl50ncbglb7ljzb66rlx8ws6dv8jm0d5siz";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.0";
    sha256 = "0nzra1i0mljvmnj1qqqg37xs7bl71fnpl68nwmdajchh65l878zr";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "11442h38fidqwhkfv00l6vgjnljfhxs9yqzyfnpf45hhh0wwsz9i";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1hacg7dqddl37rz9sm3n4kihzynjk5b8q49bv2hvillw2akp77q0";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.0.1";
    sha256 = "19cknvg07yhakcvpxg3cxa0bwadplin6kyxd8mpjjpwnp56nl85x";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.0.11";
    sha256 = "1pla2dx8gkidf7xkciig6nifdsb494axjvzvann8g2lp3dbqasm9";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.0.11";
    sha256 = "070c5jbas2v7smm660zaf1gh0489xanjqymkvafcs4f8cdrs1d5d";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.1.0";
    sha256 = "1g0yb8p11vfd0kbkyzlfsbsp5z44lwsvyc0h3dpw6vqnbi035ajp";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.0.1";
    sha256 = "0kgfpw6w4djqra3w5crrg8xivbanh1w9dh3qapb28q060wb9flp1";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.0.1";
    sha256 = "1s0mniajj3lvbyf7vfb5shp4ink5yibsx945k6lvxa96r8la1612";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "1d3aspylbzkvn12iyjycy12ygyhagci484q9zim7r2p8pdbywf9h";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.1.0";
    sha256 = "1ppg83svb39hj4hpp5k7kcryzrf3sfnm08vxd5sm2drrijsla2k5";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.1.0";
    sha256 = "1gpdxl6ip06cnab7n3zlcg6mqp7kknf73s8wjinzi4p0apw82fpg";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.0.12";
    sha256 = "1sybkfi60a4588xn34nd9a58png36i0xr4y4v4kqpg8wlvy5krrj";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.1.0";
    sha256 = "1js89429pfw79mxvbzp8p3q93il6rdff332hddhzi5wqglc4gml9";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.0.1";
    sha256 = "0ydqcsvh6smi41gyaakglnv252625hf29f7kywy2c70nhii2ylqp";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.0.1";
    sha256 = "1pcd2ig6bg144y10w7yxgc9d22r7c7ww7qn1frdfwgxr24j9wvv0";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.0.1";
    sha256 = "1s4b043zdbx9k39lfhvsk68msv1nxbidhkq6nbm27q7sf8xcsnxr";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.0.1";
    sha256 = "0m7wqwq0zqq9gbpiqvgk3sr92cbrw7cp3xn53xvw7zj6rz6fdirn";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.0.1";
    sha256 = "1bangaabhsl4k9fg8khn83wm6yial8ik1sza7401621jc6jrym28";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.1.0";
    sha256 = "1bjli8a7sc7jlxqgcagl9nh8axzfl11f4ld3rjqsyxc516iijij7";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.0.1";
    sha256 = "0b4i7mncaf8cnai85jv3wnw6hps140cxz8vylv2bik6wyzgvz7bi";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.1.0";
    sha256 = "02hdkgk13rvsd6r9yafbwzss8kr55wnj8d5c7xjnp8gqrwc8sn0m";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.1.0";
    sha256 = "0rw4rm4vsm3h3szxp9iijc3ksyviwsv6f63dng3vhqyg4vjdkc2z";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.0.1";
    sha256 = "1g0zrdi5508v49pfm3iii2hn6nm00bgvfpjq1zxknfjrxxa20r4g";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.1.0";
    sha256 = "01kxqppx3dr3b6b286xafqilv4s2n0gqvfgzfd4z943ga9i81is1";
  })
  (fetchNuGet {
    pname = "System.Runtime.Serialization.Primitives";
    version = "4.1.1";
    sha256 = "042rfjixknlr6r10vx2pgf56yming8lkjikamg3g4v29ikk78h7k";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.0.11";
    sha256 = "1dyqv0hijg265dwxg6l7aiv74102d6xjiwplh2ar1ly6xfaa4iiw";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.0.11";
    sha256 = "08nsfrpiwsg9x5ml4xyl3zyvjfdi4mvbqf93kjdh11j4fwkznizs";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    sha256 = "1wbypkx0m8dgpsaqgyywz4z760xblnwalb241d5qv9kx8m128i11";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "0ynpcmfa831wzypdnhik2rnipbin81xnz210dsirzb8kqrhgw37z";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.4";
    sha256 = "18i1vdadrw1sr74mh4byd5mzyiaiz0m30rqxd940zifpyvni76l3";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "9.0.0-preview.7.24405.7";
    sha256 = "168zq0lv45wqznkf34mpz1857nxnl8ad3f2nyj81nhql4wr70vs4";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.1.0";
    sha256 = "1mw7vfkkyd04yn2fbhm38msk7dz2xwvib14ygjsb8dq2lcvr18y7";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.0.11";
    sha256 = "19x946h926bzvbsgj28csn46gak2crv2skpwsx80hbgazmkgb1ls";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.0.11";
    sha256 = "0nr1r41rak82qfa5m0lhk9mp0k93bvfd7bbd9sdzwx9mb36g28p5";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.0.0";
    sha256 = "1cb51z062mvc2i8blpzmpn9d9mm4y307xrwi65di8ri18cz5r1zr";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.0.11";
    sha256 = "0c6ky1jk5ada9m94wcadih98l6k1fvf6vi7vhn1msjixaha419l5";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.0.11";
    sha256 = "0n4lvpqzy9kc7qy1a4acwwd7b7pnvygv895az5640idl2y9zbz18";
  })
  (fetchNuGet {
    pname = "Xabe.FFmpeg";
    version = "5.2.6";
    sha256 = "1jdmlr2j7m89lw9096l2p1j4azbayi4d57bh6ypazjw1f644qy30";
  })
  (fetchNuGet {
    pname = "YoutubeDLSharp";
    version = "1.1.1";
    sha256 = "188yz4c7fw81ydfwvw1bmqn285ahv26j485q6ipbn1j3d05cgk36";
  })
]
